name: Run Tests and Generate Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  version-updater:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure this is the latest stable version

      - name: GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1

  test:
    runs-on: ubuntu-latest
    needs: version-updater

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure this is the latest stable version

      - name: Set up Python
        uses: actions/setup-python@v4  # Ensure this is the latest version
        with:
          python-version: '3.12.7'  # Set the Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Run tests and generate Allure results
        run: |
          pytest --alluredir=allure-results

      - name: Generate Allure report
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v3  # Ensure this is the latest version
        with:
          name: allure-report
          path: allure-report  # Path to the generated report
