name: Run Tests and Generate Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]  # Optional: trigger on pull request events

jobs:
  version-updater:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1

  test:
    runs-on: ubuntu-latest
    needs: version-updater  # Ensure this runs after the version updater

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Correct version

      - name: Set up Python
        uses: actions/setup-python@v4  # Update to version 4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Run tests and generate Allure results
        run: |
          pytest --alluredir=allure-results

      - name: Generate Allure report
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
